### ISSUE TITLE
How to view player scrore?

### ISSUE THREAD

**Issue by JamshidTashpulatov** [hankolsen/melodikryzzet#1]
It's important for users

**Comment by hankolsen** [comment]
Hi @JamshidTashpulatov!
Thank you for your interest. So far this is just a very personal project where lots of things are made manual. For instance there is no way of adding the correct answers to be able to score a user.
I will continue to add features along the way, but at the moment it is used with a host reading all the questions and playing all the music for a group of contestants.

**Comment by JamshidTashpulatov** [comment]
I am also asked to prepare a crossword. But I stopped at some point. You can see my code through repo (https://github.com/JamshidTashpulatov/JQuery-krossword-game). I have someone else using the JQuery library. But there is a problem. I'm not sure how to store the user input on LocalStorage.

**Comment by JamshidTashpulatov** [comment]
I am also asked to prepare a crossword. But I stopped at some point. You
can see my code through repo (
https://github.com/JamshidTashpulatov/JQuery-krossword-game). I have
someone else using the JQuery library. But there is a problem. I'm not sure
how to store the user input on LocalStorage.
Can you help me get this done?

вт, 5 мар. 2019 г. в 12:45, hankolsen <notifications@github.com>:

**Comment by hankolsen** [comment]
I see that you have the code for adding things to localStorage and to retreive it from localStorege commented out in your main.js file
```
localStorage.setItem("ke123y", JSON.stringify(input));
let myItem = JSON.parse(localStorage.getItem("ke123y"));
```

I would recommend that you find the code where the user has entered a word, after that you store the current puzzle information into localStorage using  `localStorage.setItem('puzzleData', JSON.stringify(allData))`;

Then you also need to find where the puzzle is setup, and check localStorage if there is previous data stored with `const previosData = JSON.parse(localStorage.getItem('puzzleData'))`;
If there is previous data, use that to fill the puzzle when you create it.

You should also add a button for the user to clear any stored data that she no longer wants to show up, and remove the data with `localStorage.removeItem('puzzleData')`.
Hope that helps!
